# KNX configuration  

expose:
  - type: temperature
    entity_id: sensor.knxTemp1
    address: "2/1/2"

number:

  - name: "Master sov bryter LED %"
    address: "1/2/140"
    type: percent
    step: 10

  - name: "Bryter ved trapp LED %"
    address: "3/1/0"
    type: percent
    step: 10

  - name: "Bryter stue LED %"
    address: "3/1/4"
    type: percent
    step: 10
      
  - name: "Bryter stue kjøkken LED %"
    address: "3/1/7"
    type: percent
    step: 10

  - name: "Bryter stue TV LED %"
    address: "3/1/9"
    type: percent
    step: 10

binary_sensor:
  - name: "Bryter ved trapp VK1T"
    state_address: "3/1/10"
    reset_after: 5
    sync_state: False
      
  - name: "Bryter ved trapp VKT2"
    state_address: "3/1/23"
    reset_after: 5
    sync_state: False

  - name: "Bryter ved trapp VKB1"
    state_address: "3/1/11"
    reset_after: 5
    sync_state: False

  - name: "Bryter ved trapp VKB2"
    state_address: "3/1/12"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - VKT"
    state_address: "3/1/13"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - VKT2"
    state_address: "3/1/15"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - VKB"
    state_address: "3/1/14"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - VKB2"
    state_address: "3/1/16"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - HKT1"
    state_address: "3/1/19"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - HKT2"
    state_address: "3/1/20"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - HKB1"
    state_address: "3/1/21"
    reset_after: 5
    sync_state: False

  - name: "Bryter Stue Kitchen - HKB2"
    state_address: "3/1/22"
    reset_after: 5
    sync_state: False

  - name: "Varmepådrag vaskerom elektrisk"
    state_address: "2/0/31"

  - name: "Varmepådrag master bad"
    state_address: "2/2/17"

sensor:

  - name: "Vaskerom gulvtemp"
    state_address: "2/0/25"
    type: temperature

  - name: "Vaskerom lufttemp"
    state_address: "2/0/24"
    type: temperature
      
  - name: "Bryter ved trapp - temperatur"
    state_address: "3/1/1"
    type: temperature

  - name: "Bryter stue - temperatur"
    state_address: "3/1/3"
    type: temperature

  - name: "Bryter stue kjøkken - temperatur"
    state_address: "2/1/14"
    type: temperature

  - name: "Master bad gulvtemp"
    state_address: "2/2/14"
    type: temperature

  - name: "Master bad lufttemp"
    state_address: "2/2/13"
    type: temperature

  - name: "Loftstue temperatur"
    state_address: "2/2/2"
    type: temperature

  - name: "Master sov temperatur"
    state_address: "2/2/46"
    type: temperature

  - name: "Sov 1 temperatur"
    state_address: "2/2/24"
    type: temperature

  - name: "Sov 2 temperatur"
    state_address: "2/2/35"
    type: temperature

  - name: "Varmepådrag loftstue"
    state_address: "2/2/6"
    type: percent

  - name: "Varmepådrag kjellergang"
    state_address: "2/0/6"
    type: percent

  - name: "Varmepådrag kjellerstue"
    state_address: "2/0/17"
    type: percent

  - name: "Varmepådrag vaskerom"
    state_address: "2/0/28"
    type: percent

  - name: "Varmepådrag master sov"
    state_address: "2/2/50"
    type: percent

  - name: "Varmepådrag sov 1"
    state_address: "2/2/28"
    type: percent

  - name: "Varmepådrag sov 2"
    state_address: "2/2/39"
    type: percent

  - name: "Varmepådrag entre"
    state_address: "2/1/6"
    type: percent

  - name: "Varmepådrag stue"
    state_address: "2/1/17"
    type: percent

  - name: "Varmepådrag kjøkken"
    state_address: "2/1/28"
    type: percent

  - name: "Power potential"
    state_address: "0/0/102"
    type: electric_potential

  - name: "Power current"
    state_address: "0/0/103"
    type: electric_current

# KLIMA

climate:

# Klima i kjeller

  - name: "Kjellergang"
    temperature_address: "2/0/2"
    target_temperature_address: "2/0/5"
    target_temperature_state_address: "2/0/4"

  - name: "Kjellerstue"
    temperature_address: "2/0/13"
    target_temperature_address: "2/0/16"
    target_temperature_state_address: "2/0/15"

  - name: "Vaskerom"
    temperature_address: ["2/0/24", "2/0/25"]
    target_temperature_address: "2/0/27"
    target_temperature_state_address: "2/0/26"

# Klima i 1. etg

  - name: "Entre"
    temperature_address: "2/1/2"
    target_temperature_address: "2/1/5"
    target_temperature_state_address: "2/1/4"
    command_value_state_address: "2/0/0"

  - name: "Stue"
    temperature_address: "2/1/13"
    target_temperature_address: "2/1/16"
    target_temperature_state_address: "2/1/15"

  - name: "Kjøkken"
    temperature_address: "2/1/24"
    target_temperature_address: "2/1/27"
    target_temperature_state_address: "2/1/26"

# Klima i 2. etg

  - name: "Lekerom"
    temperature_address: "2/2/2"
    target_temperature_address: "2/2/5"
    target_temperature_state_address: "2/2/4"

  - name: "Bad"
    temperature_address: "2/2/13"
    target_temperature_address: "2/2/16"
    target_temperature_state_address: "2/2/15"
    on_off_address: "2/2/17"
    on_off_state_address: "2/2/11"

  - name: "Sov 1"
    temperature_address: "2/2/24"
    target_temperature_address: "2/2/27"
    target_temperature_state_address: "2/2/26"

  - name: "Sov 2"
    temperature_address: "2/2/35"
    target_temperature_address: "2/2/38"
    target_temperature_state_address: "2/2/37"

  - name: "Master sov"
    temperature_address: "2/2/46"
    target_temperature_address: "2/2/49"
    target_temperature_state_address: "2/2/48"

## LYS

light:
  - name: "Alt lys"
    address: "0/0/1"

##############################################
# Lys i kjeller
  
  - name: "Vaskerom"
    address: "1/0/143"
    state_address: "1/0/146"
    brightness_address: "1/0/145"
    brightness_state_address: "1/0/147"

  - name: "Kjellerstue"
    address: "1/0/125"
    state_address: "1/0/128"
    brightness_address: "1/0/127"
    brightness_state_address: "1/0/129"

  - name: "Kjellergang"
    address: "1/0/107"
    state_address: "1/0/110"
    brightness_address: "1/0/109"
    brightness_state_address: "1/0/111"

###############################################
# Lys i trapp

#  - name: "Trapp taklys"
#    address: "1/1/180"
#    state_address: "1/1/183"
#    brightness_address: "1/1/181"
#    brightness_state_address: "1/1/184"


###############################################
# LYS i stue 1. etg

  - name: "Alt lys i stue"
    address: "1/1/42"
    state_address: "1/1/45"
    brightness_address: "1/1/44"
    brightness_state_address: "1/1/47"

  - name: "Alt lys på kjøkken"
    address: "1/1/84"
    state_address: "1/1/87"
    brightness_address: "1/1/86"
    brightness_state_address: "1/1/88"

  - name: "Stue spotter ved kunst"
    address: "1/1/48"
    state_address: "1/1/51"
    brightness_address: "1/1/50"
    brightness_state_address: "1/1/52"

  - name: "Stue downlights ved bokhylle"
    address: "1/1/54"
    state_address: "1/1/57"
    brightness_address: "1/1/56"
    brightness_state_address: "1/1/58"

  - name: "Stue downlights ved daybed"
    address: "1/1/60"
    state_address: "1/1/63"
    brightness_address: "1/1/62"
    brightness_state_address: "1/1/64"

  - name: "Stue downlight ved trapp"
    address: "1/1/66"
    state_address: "1/1/69"
    brightness_address: "1/1/68"
    brightness_state_address: "1/1/70"

###############################################
# Lys på kjøkken i 1. etg

  - name: "Kjøkken downlight sone 1"
    address: "1/1/90"
    state_address: "1/1/93"
    brightness_address: "1/1/92"
    brightness_state_address: "1/1/94"

  - name: "Kjøkken downlight sone 2"
    address: "1/1/96"
    state_address: "1/1/99"
    brightness_address: "1/1/98"
    brightness_state_address: "1/1/100"

  - name: "Kjøkken lys benk"
    address: "1/1/102"
    state_address: "1/1/105"
    brightness_address: "1/1/104"
    brightness_state_address: "1/1/106"

  - name: "Kjøkken spisebord"
    address: "1/1/108"
    state_address: "1/1/111"
    brightness_address: "1/1/110"
    brightness_state_address: "1/1/112"

  - name: "Kjøkken led list"
    address: "1/1/114"
    state_address: "1/1/117"
    brightness_address: "1/1/116"
    brightness_state_address: "1/1/118"

  - name: "Kjøkken reserve 2"
    address: "1/1/126"
    state_address: "1/1/129"
    brightness_address: "1/1/128"
    brightness_state_address: "1/1/130"

  - name: "Kjøkken reserve 1"
    address: "1/1/120"
    state_address: "1/1/123"
    brightness_address: "1/1/121"
    brightness_state_address: "1/1/124"


#############################################
# Lys på kjøkken spiseområde

  - name: "Spisestue downlight sone 1"
    address: "1/1/138"
    state_address: "1/1/141"
    brightness_address: "1/1/140"
    brightness_state_address: "1/1/142"

  - name: "Spisestue downlight sone 2"
    address: "1/1/144"
    state_address: "1/1/147"
    brightness_address: "1/1/146"
    brightness_state_address: "1/1/148"

  - name: "Spisestue led list"
    address: "1/1/150"
    state_address: "1/1/153"
    brightness_address: "1/1/152"
    brightness_state_address: "1/1/154"

  - name: "Spisestue taklys"
    address: "1/1/156"
    state_address: "1/1/159"
    brightness_address: "1/1/158"
    brightness_state_address: "1/1/160"

###############################################
# Lys i Entre 1. etg

  - name: "Entre downlights"
    address: "1/1/6"
    state_address: "1/1/9"
    brightness_address: "1/1/8"
    brightness_state_address: "1/1/10"

  - name: "WC-rom taklys"
    address: "1/1/30"
    state_address: "1/1/33"
    brightness_address: "1/1/32"
    brightness_state_address: "1/1/34"

# LYS 2. etg

##############################################
# Master sov

  - name: "Master sov spotter"
    address: "1/2/108"
    state_address: "1/2/111"
    brightness_address: "1/2/110"
    brightness_state_address: "1/2/112"

  - name: "Master sov skap Haakon"
    address: "1/2/120"
    state_address: "1/2/123"
    brightness_address: "1/2/122"
    brightness_state_address: "1/2/124"

  - name: "Master sov skap Katharina"
    address: "1/2/126"
    state_address: "1/2/129"
    brightness_address: "1/2/128"
    brightness_state_address: "1/2/130"

##############################################
# SOV 1

  - name: "Soverom 1 downlights"
    address: "1/2/60"
    state_address: "1/2/63"
    brightness_address: "1/2/62"
    brightness_state_address: "1/2/64"

  - name: "Soverom 1 taklys"
    address: "1/2/66"
    state_address: "1/2/69"

##############################################
# SOV 2

  - name: "Soverom 2 downlights"
    address: "1/2/84"
    state_address: "1/2/87"
    brightness_address: "1/2/86"
    brightness_state_address: "1/2/88"

  - name: "Soverom 2 taklys"
    address: "1/2/90"
    state_address: "1/2/93"

##############################################
# Loftstue

  - name: "Loftstue downlights"
    address: "1/2/6"
    state_address: "1/2/9"
    brightness_address: "1/2/8"
    brightness_state_address: "1/2/10"

  - name: "Loftstue taklys"
    address: "1/2/12"
    state_address: "1/2/15"
    brightness_address: "1/2/14"
    brightness_state_address: "1/2/16"

##############################################
# Bad
  
  - name: "Bad downlights"
    address: "1/2/36"
    state_address: "1/2/39"
    brightness_address: "1/2/38"
    brightness_state_address: "1/2/40"

  - name: "Bad speil"
    address: "1/2/42"
    state_address: "1/2/45"
    brightness_address: "1/2/44"
    brightness_state_address: "1/2/46"

  - name: "Bad dusj"
    address: "1/2/48"
    state_address: "1/2/51"
    brightness_address: "1/2/50"
    brightness_state_address: "1/2/52"


# Config for relays
switch:
  - name: "Tvangskjøring varme"
    address: "0/0/200"

  - name: "Tvangskjøring varme 2.etg"
    address: "0/0/202"

  - name: "Master sov bryter TA"
    address: "1/2/141"

  - name: "Bryter ved trapp TA"
    address: "3/1/2"


  - name: "Bryter stue TA"
    address: "3/1/5"

  - name: "Bryter stue kjøkken TA"
    address: "3/1/6"

  - name: "Bryter stue TV TA"
    address: "3/1/8"

  - name: "Master sov LED L2 Green"
    address: "1/2/138"

  - name: "Master sov LED L2 Blue"
    address: "1/2/139"

  - name: "Entre bryter knapp 3 - MASTER PÅ/AV"
    address: "1/1/198"

  - name: "Stikk ved sofa"
    address: "0/1/0"
    state_address: "0/1/1"

  - name: "Stikk ved daybed"
    address: "0/1/2"
    state_address: "0/1/3"

  - name: "Stikk loftstue"
    address: "0/1/4"
    state_address: "0/1/5"

  - name: "Håndkletørkere"
    address: "0/1/6"
    state_address: "0/1/7"

# Regular on/off lights
  - name: "Utelys"
    address: "0/0/10"
    state_address: "0/0/11"

  - name: "Trapp plan 1"
    address: "1/1/186"
    state_address: "1/1/189"

  - name: "Trapp plan 2"
    address: "1/1/192"
    state_address: "1/1/195"

  - name: "Entre vegglys"
    address: "1/1/12"
    state_address: "1/1/15"

  - name: "WC-rom speil"
    address: "1/1/36"
    state_address: "1/1/39"

