# KNX configuration  
number: !include knx/number.yaml
binary_sensor: !include knx/binary_sensor.yaml
sensor: !include knx/sensor.yaml
climate: !include knx/climate.yaml
light: !include knx/lights.yaml
switch: !include knx/switch.yaml
