esphome:
  name: wifi-home
  friendly_name: Wifi Home

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "123oftah6NO5cEGohnshfrpL4Noan6zZlXjHlj/xfpA="

ota:
  platform: esphome
  password: "1ef67f6322f1d175d7d72355ff6ba138"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Wifi-Home Fallback Hotspot"
    password: "CWkgJt67dCQg"
    
sensor:
  - platform: dht
    pin: 6
    temperature:
      name: "Test temp"
    humidity:
      name: "Test humid"
    update_interval: 60s
